# Generated by Django 5.0 on 2024-01-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
