# Generated by Django 5.0 on 2024-01-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_song_id_song_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
